<?php
	
/*
	Question2Answer 1.3.1 (c) 2011, Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-options.php
	Version: 1.3.1
	Date: 2011-02-01 12:56:28 GMT
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
                'place_full_below_content' => 'عرض کامل-زیر محتوا',
                'place_full_below_footer' => 'عرض کامل-زیر فوتر',
                'place_main_below_lists' => 'صفحه اصلی - در زیر لیست',
                'place_main_below_title' => 'صفحه اصلی - زیر عنوان',
                'place_main_bottom' => 'صفحه اصلی-پایین',
                'place_main_top' => 'صفحه اصلی-بالا',
                'place_side_below_categories' => 'پنل جانبی-زیر دسته ها',
                'place_side_below_sidebar' => 'سمت پنل-زیر جعبه کناری',
                'place_side_last' => 'سمت پنل-آخر',
                'place_full_top' => 'عرض کامل بالای صفحه',
                'mailing_enabled' => 'فعال کردن پست جمعی برای تمام کاربران',
                'mailing_from_name' => 'نام و نام خانوادگی:',
                'mailing_from_email' => 'از آدرس ایمیل شما:',
                'mailing_subject' => 'خط موضوع مقاله:',
                'mailing_body' => 'متن:',
                'mailing_per_minute' => 'حداکثر اندازه پست:',
                'default_subject' =>'یک پیام از ^',
                'page_size_activity' => 'طول تمام صفحه:',
                'page_size_hot_qs' => 'طوا صفحه داغ!:',
                'search_module' => 'استفاده از ماژول جستجو در:',
                'option_default' => 'پیش فرض',
                'hot_weight_q_age' => 'سوال جدید:',
                'hot_weight_a_age' => 'سوال پاسخ جدید دارد',
                'hot_weight_answers' => 'سوال پاسخ زیادی دارد',
                'hot_weight_votes' => 'سوال نظرات زیادی دارد',
                'site_theme_mobile' => 'تم برای موبایل:',
                'smtp_active' => 'ارسال ایمیل از طریق SMTP به جای نامه های محلی',
                'smtp_address' => 'SMTP آدرس سرور:',
                'smtp_port' => 'پورت SMTP سرور:',
                'smtp_authenticate' => 'ارسال نام کاربری و رمز عبور SMTP',
                'smtp_username' => 'SMTP نام کاربری:',
                'smtp_password' => 'SMTP رمز عبور:',
                'show_notice_visitor' => 'توجه داشته باشید در بالا برای بازدید کنندگان اولین بار - HTML مجاز:',
                'show_custom_register' => 'پیام های سفارشی در فرم ثبت نام - HTML مجاز:',
                'show_notice_welcome' => 'توجه داشته باشید در بالا برای کاربران تازه ثبت نام شده - HTML مجاز:',
                'show_custom_welcome' => 'پیام های سفارشی در ایمیل ارسال شده به کاربران ثبت نام شده:',
                'allow_login_email_only' => 'فقط با (آدرس ایمیل (نام کاربری به سیستم وارد شوید:',
                'allow_change_usernames' => 'اجازه می دهد تا کاربران با پست نام کاربری خود را تغییر دهید:',
                'allow_private_messages' => 'ارسال پیام خصوصی بین کاربران فعال:',
                'show_message_history' => 'ذخیره سازی و نمایش تاریخچه پیام خصوصی:',
                'place_side_below_sidebar' => 'پانل سمت - زیر جعبه نوار کناری',
                'place_side_top' => 'پنل جانبی-بالا',
                'place_full_below_nav' => 'عرض کامل-زیر ناوبری',
                'place_full_to' => 'عرض کامل-بالای صفحه',
                'do_close_on_select' => 'بستن پرسش ها با پاسخ انتخاب شده:',
                'allow_close_questions' => 'اجازه دادن به سوالات برای بسته شدن دستی',
                'allow_self_answer' => 'به کاربران اجازه می دهد سوال خود را پاسخ دهند',
                'show_custom_ask' => 'پیام دلخواه در فرم بپرسید-HTML-مجاز:',
                'extra_field_active' => 'زمینه سفارشی برای اطلاعات بیشتر در فرم بپرسید:',
                'show_custom_answer' => 'پیام های سفارشی در فرم پاسخ - HTML مجاز:',
                'show_custom_comment' => 'پیام های سفارشی در فرم نظر - HTML مجاز:',
                'tag_separator_comma' => 'استفاده از کاما به عنوان تنها جداکننده تگ ها:',
                'notify_users_default' => 'چک کردن ایمیل اطلاع رسانی جعبه به طور پیش فرض:',
                'q_urls_title_length' => 'طول عنوان سوال در آدرس ها:',
                'q_urls_remove_accents' => 'حذف لهجه ها از URL سوال:',
                'do_count_q_views' => 'تعداد نمایش ها:',
                'links_in_new_window' => 'URL های مرتبط را در یک پنجره جدید باز کنید:',
                'show_full_date_days' => 'نمایش تاریخ بعد از:',
                'page_size_q_as' => 'جداگثر تعداد پاسخ در هر صفحه:',
                'show_fewer_cs_from' => 'نیمه پنهان کردن نظرات اگر بیش از:',
                'show_fewer_cs_count' => 'اگر قسمتی پنهان شده-جدیدترین ها را نشان می دهد',
                'allow_no_sub_category' => 'اجازه پرسش با دسته و بدون زیر دسته',
                'permit_delete_users' => 'حذف کاربران:',
                'feed_for_hot' => 'خوراک برای سوالات داغ:',
                'points_per_q_voted_up' => 'هر رای بالا به سوالات شما:',
                'points_per_q_voted_down' => 'هر رای پایین به سوالات شما',
                'points_per_a_voted_up' => 'هر رای بالا به پاسه های شما',
                'points_per_a_voted_down' => 'هر رای پایین به پاسخ های شما',
                'confirm_user_required' => 'کاربران جدید با تائید کامل',
                'suspend_register_users' => 'به تغلیق در آوردن ثبت نام کاربران جدید',
                'captcha_module' => 'استفاده از ماژول کپچا:',
                'moderate_unconfirmed' => 'استفاده از اعتدال اگر ایمیل تایید نشده:',
                'moderate_by_points' => 'استفاده از اعتدال برای کاربران با چند نکته:',
                'moderate_notify_admin' => 'زمانی گه یک پست نیاز به اعتدال دارد به من ایمیل بزن',
                'flagging_of_posts' => 'اجازه پرجن دار شدن پست',
                'flagging_notify_first' => 'اگر پستی دریافت شد به من ایمیل بزن',
                'flagging_notify_every' => 'بعد از هر چیزی که اضافه شد به من ایمیل بزن',
                'flagging_hide_after' => 'پست های رسیده رو به صورت خودکار پنهان کن',
                'max_rate_ip_registers' => 'محدودیت اندازه ثبت نام کاربران',
                'max_rate_ip_flags' => 'محدودیت اندازه برای سوالات پرجم دار',
                'max_rate_ip_uploads' => 'اندازه اپلود فایلها',
                'max_rate_ip_messages' => 'حد اکثر ارسال پیام خصوصی',
		'allow_multi_answers' => 'هر کاربر مجاز به ارسال چند پاسخ به يک پرسش باشد:',
		'allow_no_category' => 'پرسش می تواند فاقد موضوع/طبقه بندی باشد',
		'avatar_allow_gravatar' => 'انتخاب ^1Gravatar^2 مجاز است:',
		'avatar_allow_upload' => 'کاربران مجاز به آپلود آواتار خود باشند:',
		'avatar_default_show' => 'نمایش آواتار پیشگزیده:',
		'avatar_profile_size' => 'اندازه آواتار در نمایه کاربران(pixels):',
		'avatar_q_list_size' => 'اندازه آواتار در فهرست پرسشها(pixels):',
		'avatar_q_page_a_size' => 'اندازه آواتار در فهرست پاسخها(pixels):',
		'avatar_q_page_c_size' => 'اندازه آواتار در نظرها(pixels):',
		'avatar_q_page_q_size' => 'اندازه آواتار در پرسشها(pixels):',
		'avatar_store_size' => 'حداکثر اندازه آواتار(pixels):',
		'avatar_users_size' => 'اندازه آواتار در صفحه شخصی کاربران(pixels):',
		'block_bad_words' => 'کلمات سانسور شده(توسط فضای خالی و یا کاما جدا شوند):',
		'block_ips_write' => 'آی پی های بلاک شده(توسط فضای خالی و یا کاما جدا شوند):',
		'captcha_on_anon_post' => 'استفاده از reCAPTCHA برای پستهای ناشناس:',
		'captcha_on_feedback' => 'استفاده از reCAPTCHA در فرم بازخورد:',
		'captcha_on_register' => 'استفاده از reCAPTCHA در ثبت نام کاربران جدید:',
		'captcha_on_reset_password' => 'استفاده از reCAPTCHA فرم نوسازی گذرواژه:',
		'captcha_on_unconfirmed' => 'استفاده از reCAPTCHA برای پستها در صورت عدم تایید ایمیل:',
		'columns_tags' => 'تعداد ستوهای برچسب در صفحه:',
		'columns_users' => 'تعداد ستونهای کاربران در صفحه:',
		'comment_on_as' => 'اجازه ثبت نظر برای پاسخها:',
		'comment_on_qs' => 'اجازه ثبت نظر برای پرسشها:',
		'confirm_user_emails' => 'درخواست تایید ایمیل برای فعالسازی کاربران جدید:',
		'custom_home_content' => 'محتوای قابل نمایش در صفحه اصلی(HTML):',
		'custom_home_heading' => 'عنوان سربرگ صفحه اصلی:',
		'custom_welcome' => 'پیام سفارشی که در ایمیلهای ارسالی به کاربران ، به پسامهای پیشگزیده اضافه می شود:',
		'default_privacy' => 'حریم خصوصی:ایمیل شما جهت مقاصد تجاری و تبلیغاتی مورد استفاده قرار نخواهد گرفت.',
		'default_sidebar' => "به ^ خوش آمدید, این سامانه به شما امکان می دهد پرسشهای خود را طرح نموده و در کوتاهترین زمان ، پاسخ خود را دریافت نمایید.",
		'default_suffix' => 'پرسش و پاسخ',
		'do_ask_check_qs' => 'بررسی پرسشهای مشابه زمان طرح پرسش جدید:',
		'do_complete_tags' => 'زمان تایپ ، برچسبهای مشابه نمایش داده شوند:',
		'do_example_tags' => 'سمان طرح پرسش نمونه برچسب ها نمایش داده شوند:',
		'do_related_qs' => 'پرسشهای مرتبط زمان طرح پرسش نمایش داده شود:',
		'editor_for_as' => 'ویرایشگر پیشگزیده پاسخ:',
		'editor_for_cs' => 'ویرایشگر پیشگزیده نظر:',
		'editor_for_qs' => 'ویرایشگر پیشگزیده پرسش:',
		'email_privacy' => 'عبارت حریم خصوصی پیشگزیده برای تمامی ایمیل های ارسالی(HTML):',
		'feed_for_activity' => 'خوراک برای آخرین فعالیتها:',
		'feed_for_qa' => 'خوراک برای آخرین پرسشها . پاسخها:',
		'feed_for_questions' => 'خوراک برای آخرین پرسشها:',
		'feed_for_search' => 'خوراک برای نتایج جستجو:',
		'feed_for_tag_qs' => 'خوراک برای آخرین پرسشهای دارای برچسب مشخص:',
		'feed_for_unanswered' => 'خوراک برای آخرین پرسشهای بدون جواب:',
		'feed_full_text' => 'خوراک شامل متن کامل باشد:',
		'feed_number_items' => 'حداکثر تعداد اقلام در هر خوراک:',
		'feed_per_category' => 'خوراک برای هر موضوع/طبقه بندی:',
		'feedback_email' => 'امیل مورد استفاده جهت ارسال پیامها از فرم بازخورد-به کاربران نمایش داده نخواهد شد:',
		'feedback_enabled' => 'فرم ارسال بازخورد فعال باشد؟',
		'follow_on_as' => 'امکان برقرار کردن ارتباط بین پرسش و پاسخهای احتمالی:',
		'from_email' => 'ایمیل مورد استفاده بعنوان فرستنده در تمامی پیامهای ارسالی توسط مدیر:',
		'logo_height' => 'ارتفاع لوگو بر حسب پیکسل:',
		'logo_show' => 'نمایش لوگو در صفحات',
		'logo_url' => 'URL مربوط به لوگو(نسبی یا مطلق):',
		'logo_width' => 'عرض لوگو بر حسب پیکسل:',
		'match_1' => 'نزدیکترین',
		'match_2' => 'نزدیکتر',
		'match_3' => 'پیش گزیده',
		'match_4' => 'دورتر',
		'match_5' => 'دورترین',
		'match_ask_check_qs' => 'تطبیق پرسشهای مشابه:',
		'match_example_tags' => 'تطبیق با برچسبهای نمونه:',
		'match_related_qs' => 'تطبیق با پرسشهای مرتبط:',
		'max_len_q_title' => 'حداکثر حروف در عنوان پرسش:',
		'max_num_q_tags' => 'حداکثر برچسبهای قابل درج/انتخاب در پرسش:',
		'max_rate_ip_as' => 'حداکثر پاسخهای قابل ثبت توسط آی پی مشخص در هر ساعت:',
		'max_rate_ip_cs' => 'حداکثر تعداد نظر های ثبت شده از یک آی پی در هر ساعت:',
		'max_rate_ip_logins' => 'حداکثر دفعات مجاز ورود ناموفق از یک آی پی در هر ساعت:',
		'max_rate_ip_qs' => 'حداکثر پرسشهای قابل ثبت از هر آی پی در هر ساعت:',
		'max_rate_ip_votes' => 'حداکثر رای داده شده از یک آی پی در هر ساعت:',
		'max_rate_user_as' => 'حداکثر پاسخها توسط هر کاربر در هر ساعت:',
		'max_rate_user_cs' => 'حداکثر نظرها توسط هر کاربر در هر ساعت:',
		'max_rate_user_qs' => 'حداکثر پرسشها توسط هر کاربر در هر ساعت:',
		'max_rate_user_votes' => 'حداکثر آراء توسط هر کاربر در هر ساعت:',
		'min_len_a_content' => 'حداقل تعداد حروف در هر پاسخ:',
		'min_len_c_content' => 'حداقل تعداد حروف در هر نظر:',
		'min_len_q_content' => 'حداقل تعداد حروف در متن پرسش:',
		'min_len_q_title' => 'حداقل حروف در عنوان پرسش:',
		'min_num_q_tags' => 'حداقل برچسب در هر پرسش:',
		'neat_urls' => 'ساختار URL در نمایش اطلاعات سایت:',
		'notify_admin_q_post' => 'زمان درج پرسش جدید،مراتب به ایمیل مقابل اطلاع داده شود:',
		'page_size_ask_check_qs' => 'حداکثر پرسشهای مشابه قابل نمایش:',
		'page_size_ask_tags' => 'حداکثر برچسبهای احتمالی جهت نمایش:',
		'page_size_home' => 'اندازه صفحه اصلی:',
		'page_size_qs' => 'اندازه صفحه پرسشها:',
		'page_size_related_qs' => 'حداکثر تعداد پرسشهای مرتبط:',
		'page_size_search' => 'تعداد پرسشها در نتیجه جستجو:',
		'page_size_tag_qs' => 'تعداد پرسشهای نتیجه انتخاب برچسب:',
		'page_size_tags' => 'اندازه صفحه برچسب:',
		'page_size_una_qs' => 'اندازه صفحه پرسشهای فاقد پاسخ:',
		'page_size_user_posts' => 'تعداد پست ها در صفحه کاربر:',
		'page_size_users' => 'اندازه صفحه کاربر:',
		'pages_prev_next' => 'پیوند به صفحه قبلی/بعدی:',
		'permit_admins' => 'مدیران',
		'permit_all' => 'هر کسی',
		'permit_anon_view_ips' => 'مشاهده آی پی کاربرن ناشناس:',
		'permit_block' => 'امکان بلاک کردن کاربران/آی پی:',
		'permit_confirmed' => 'ثبت نام کاربران جدید همراه با تایید ایمیل باشد',
		'permit_create_admins' => 'ایجاد مدیر:',
		'permit_create_eds_mods' => 'ایجاد ناظم:',
		'permit_create_experts' => 'ایجاد کاربر خبره:',
		'permit_delete_hidden' => 'حذف پستهای مخفی:',
		'permit_edit_a' => 'اصلاح همه پاسخها:',
		'permit_edit_c' => 'اصلاح همه نظرها:',
		'permit_edit_q' => 'اصلاح همه پرسشها:',
		'permit_editors' => 'بازنگرها, ناظم ها, مدیران',
		'permit_experts' => 'خبره ها, بازنگرها, ناظم ها, مدیران',
		'permit_hide_show' => 'مخفی سازی هر پستی:',
		'permit_moderators' => 'ناظم ها و مدیرن',
		'permit_post_a' => 'درج پاسخ:',
		'permit_post_c' => 'درج نظر:',
		'permit_post_q' => 'درج پرسش:',
		'permit_see_emails' => 'مشاهده ایمیل کاربران:',
		'permit_select_a' => 'انتخاب یک پاسخ برای تمام پرسشها:',
		'permit_supers' => 'مدیران ارشد',
		'permit_users' => 'کاربران عضو',
		'permit_vote_a' => 'رای دادن به پاسخها:',
		'permit_vote_q' => 'رای دادن به پرسشها:',
		'points_a_selected' => 'امکان انتخاب پاسخ ها بعنوان بهترین پاسخ:',
		'points_a_voted_max_gain' => 'محدودیت رای دادن به هر پاسخ:',
		'points_a_voted_max_loss' => 'محدودیت رای منفی به هر پاسخ:',
		'points_base' => 'برای همه کاربران جمع شود:',
		'points_multiple' => 'برای همه کاربران امتیاز ها ضرب شود:',
		'points_per_a_voted' => 'به ازای هر پاسخ ، امتیاز مثبت و منفی محاسبه شود:',
		'points_per_q_voted' => 'به ازای هر پرسش ، امتیاز مثبت و منفی محاسبه شود:',
		'points_post_a' => 'ارسال یک پاسخ:',
		'points_post_q' => 'ارسال یک پرسش:',
		'points_q_voted_max_gain' => 'محدود کردن ثبت رای مثبت برای پرسشها:',
		'points_q_voted_max_loss' => 'محدود کردن ثبت رای منفی به پرسشها:',
		'points_select_a' => 'امکان انتخاب بهترین پاسخ برای یک پرسش:',
		'points_vote_down_a' => 'امکان درج رای منفی به یک پاسخ:',
		'points_vote_down_q' => 'امکان درج رای منفی به یک پرسش:',
		'points_vote_up_a' => 'امکان درج رای مثبت به یک پاسخ:',
		'points_vote_up_q' => 'امکان درج رای مثبت به یک پرسش:',
		'recaptcha_private_key' => 'کد reCAPTCHA خصوصی شما:',
		'recaptcha_public_key' => 'کد reCAPTCHA عمومی شما:',
		'show_a_form_immediate' => 'نماسش فوری فرم پاسخ:',
		'show_always' => 'همیشه',
		'show_c_reply_buttons' => 'نمایش دکمه پاسخ در زیر نظر ها:',
		'show_custom_footer' => 'HTML سفارشی در پاورقی همه صفحات:',
		'show_custom_header' => 'HTML سفارشی در سربرگ همه صفحات:',
		'show_custom_home' => 'محتوای سفارشی در صفحه نخست(HTML)',
		'show_custom_in_head' => 'HTML سفارشی در <HEAD> همه صفحات:',
		'show_custom_sidebar' => 'HTML سفارشی در نوار جانبی همه صفحات:',
		'show_custom_sidepanel' => 'HTML سفارشی در پانل جانبی همه صفحات:',
		'show_home_description' => 'درج <META> برای صفحه نخست:',
		'show_if_no_as' => 'اگر فاقد پاسخ باشد',
		'show_never' => 'هیچگاه',
		'show_selected_first' => 'پاسخهای زیر به ابتدای فهرست منتقل شوند:',
		'show_url_links' => 'نمایش URL پیوندها:',
		'show_user_points' => 'نمایش امتیاز کاربران:',
		'show_user_titles' => 'نمایش عنوان/مدال کاربران:',
		'show_when_created' => 'نمایش سن کاربران:',
		'site_language' => 'زبان سایت:',
		'site_maintenance' => 'سایت جهت عملیات نگهداری غیر فعال گردد',
		'site_theme' => 'قالب فعلی سایت:',
		'site_title' => 'عنوان تارنما:',
		'site_url' => 'نشانی URL جهت ارجاع به این تارنما:',
		'sort_answers_by' => 'مرتب سازی پاسخها بر اساس:',
		'sort_time' => 'زمان',
		'sort_votes' => 'رأی ها',
		'tags_or_categories' => 'طبقه بندی پرسشها بر اساس:',
		'votes_separated' => 'نمایش دکمه کم/زیاد برای ثبت رأی:',
		'voting_on_as' => 'امکان درج رأی برای پاسخها:',
		'voting_on_q_page_only' => 'امکان درج رای تنها در صفحه پرسشها مقدور باشد:',
		'voting_on_qs' => 'امکان ثبت رای برای پرسشها:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
