<?php
	
/*
	Question2Answer 1.5.4 (c) 2011, Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-admin.php
	Version: 1.3.1
	Date: 2011-02-01 12:56:28 GMT
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
                'version_latest'=>'آخرین نسخه',
                'version_get_x'=>'دریافت نسخه جدید',
                'add_widget_button' => 'Add Widge',
                'add_widget_link' => ' – ^1add widget^',
                'active_widgets_explanation' => 'Currently active widgets:',
	        'delete_widget_position' => 'حذف این عنصر از این موقعیت',
                'widget_all_pages' => 'نمایش ویدجت در این موقعیت در تمامی صفحات', 
                'widget_pages_explanation' => 'نمایش ویجت در این موقعیت در صفحات زیر:',
                'question_lists' => 'لیست سوالات',
                'user_pages' => 'صفحه کاربر',
                'tag_pages' => 'صفحه برچسب ها',
                'widget_name' => 'نام ویدجت:',
                'delete_widget_position' => 'حذف این عنصر از این موقعیت',
                'question_pages' => 'صفحه سوالات',
                'ip_address_pages' => 'صفحات آدرس IP',
                'characters' => 'کاراکتر',
                'no_flagged_found' => 'هیچ محتوای پرچم یافت',
                'flagged_title' => 'پرچم',
                'moderate_title' => 'متوسط',
                'no_approve_found' => 'هیچ محتوایی برای تائید نیست',
                'mailing_title' => 'پستی',
                'mailing_explanation' => 'کاربرا میتوانند حساب خود را لغو کنند',
                'emails_per_minute' => 'ایمیل در هر دقیقه',
                'mailing_complete' => 'پست کامل است',
                'start_mailing_button' => 'شروع پست',
                'send_test_button' => 'ارسال تست به من',
                'mailing_unsubscribe' => 'لینک لغو عضویت در پایینهر پیام اضافه خواهد شد',
                'hotness_factors' => 'اهمیت نسبی برای محبوبیت سوال:',
                'lists_title' => 'لیست',
                'check_language_suffix' => ' - ^1برسی فایل های زبان^2',
                'pixels' => 'پیکسل',
                'widgets_explanation' => 'ویدجت های موجود:',
                'widget_global_options' => ' - ^1انتحابها^2',
                'top_level_categories' => 'دسته بندی های سطح بالا:',
                'plugin_module' => ' (ماژول پلاگین: ^)',
                'permit_to_view' => 'قابل مشاهده برای:',
                'options' => 'انتخابها',
                'per_ip_hour' => 'هر/IP/ساعت',
                'per_user_hour' => 'هر/گاربر/ساعت',
                'q2a_build_date' => 'ساخت تاریخ',
                'q2a_db_size' => 'اندازه بانک اطلاعاتی:',
                'reindex_content_note' => ' - برای جستجو و پیشنهادات مرتبط با سوال',
                'reindex_content' => 'توقف نمایه سازی',
                'refill_events_note' => ' - برای هر کاربر\'فهرست به روز رسانی',
                'refill_events' => 'دوباره پر کردن جریان رویداد',
                'refill_events_refilled' => 'پر برای ^1 of ^2 سوالات...',
                'module_x_database_init' => 'این ^1 ^2 ماژول نیاز به ^3مقدار دهی اولیه پایگاه داده دارد^4.',
                'add_widget_button' => 'اضافه کردن ویدجت',
                'add_widget_link' => ' – ^1اضافه کردن ویدجتt^',
                'active_widgets_explanation' => 'ویدجت در حال حاضر فعال',
                'add_category_button' => 'طبقه بندی جدید',
		'add_field_button' => 'فیلد جدید',
		'add_link_button' => 'پیوند جدید',
		'add_link_link' => ' - ^1پیوند جدید^2',
		'add_new_field' => 'افزودن فیلد جدید',
		'add_new_title' => 'افزودن عنوان جدید',
		'add_page_button' => 'صفحه جدید',
		'add_title_button' => 'عنوان جدید',
		'admin_title' => 'مرکز مدیریت',
		'after_footer' => 'پس از فیلدهای پاورقی',
		'after_main_menu' => 'پس از منوی اصلی',
		'after_x_tab' => 'پس از "^" منوی اصلی',
		'after_x' => 'پس از "^"',
		'basic_editor' => 'ویرایشگر معمولی',
		'before_main_menu' => 'قبل از منوی اصلی',
		'block_ips_note' => 'مثلا: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => 'مثلا: doh (will only match exact word doh) , doh* (will match doh or dohno) , do*h (will match doh, dooh, dough).',
		'categories_introduction' => 'برای آغاز طبقه بندی بر روی دکمه \'طبقه بندی جدید\' کلیک نمایید.',
		'categories_not_shown' => 'برخی پرسشها دارای طبقه بندی هستند که در اینجا نمایش داده نخواهند شد.',
		'categories_title' => 'طبقه بندیها',
		'categories' => 'طبقه بندیها',
		'category_already_used' => 'این عنوان تکراری است',
		'category_default_slug' => 'category-^',
		'category_name_first' => 'عنوان اولین طبقه بندی:',
		'category_name' => 'عنوان طبقه بندی:',
		'category_position' => 'مکان در فهرست طبقه بندیها:',
		'category_slug' => 'عبارت مستعار طبقه بندی(URL fragment):',
		'click_category_edit' => 'جهت اصلاح ، بر روی طبقه بندی مورد نظر کلیک کنید:',
		'click_name_edit' => 'صفحات یا پیوند های سفارشی:',
		'database_cleanup' => 'عملیات پاکسازی بانک اطلاعاتی',
		'delete_category_reassign' => 'حذف این طبقه بندی و انتقال موضوعات آن به طبقه بندی دیگر:',
		'delete_category' => 'حذف این طبقه بندی',
		'delete_field' => 'حذف این فیلد',
		'delete_hidden_complete' => 'همه پستهای مخفی به استثنای پستهای وابسته به آن حذف شدند.',
		'delete_hidden_note' => ' - همه پستها ، پرسشها و پاسخهای مخفی بدون وسوابق وابسته به آنها',
		'delete_hidden' => 'حذف پستهای مخفی',
		'delete_link' => 'حذف این پیوند',
		'delete_page' => 'حذف این صفحه',
		'delete_stop' => 'توقف عملیات حذف',
		'delete_title' => 'حذف این عنوان',
		'edit_custom_page' => 'اصلاح صفحه سفارشی',
		'edit_field' => ' - ^1اصلاح فیلد^2',
		'edit_link' => ' - ^1اصلاح پیوند^2',
		'edit_page' => ' - ^1اصلاح صفحه^2',
		'edit_title' => ' - ^1اصلاح عنوان^2',
		'emails_title' => 'پستهای الکترونیکی',
		'feed_link_example' => 'خوراک نمونه',
		'feed_link' => 'خوراک',
		'feeds_title' => 'خوراک ها',
		'field_link_url' => 'URL پیوند شده',
		'field_multi_line' => 'متن چند خطی',
		'field_name' => 'نام نمایشی فیلد:',
		'field_single_line' => 'متن تک خطی',
		'field_type' => 'نوع فیلد:',
		'first' => 'اولین',
		'from_anon' => 'از ناشناس:',
		'from_plugin' => ' (از افزونه: ^)',
		'from_users' => 'از کاربرن:',
		'general_title' => 'عمومی',
		'hidden_answers_deleted' => '^1 از ^2 پاسخهای مخفی حذف گردید...',
		'hidden_comments_deleted' => '^1 از ^2 از نظر های مخفی حذف گردید...',
		'hidden_questions_deleted' => '^1 از ^2 پرسشهای مخفی حذف گردید...',
		'hidden_title' => 'مخفی',
		'installed_plugins' => 'افزونه های نصب شده:',
		'layout_title' => 'لایه',
		'link_name' => 'متن پیوند:',
		'link_new_window' => 'پیوند در صفحه جدید باز شود',
		'link_url' => 'نشانی پیوند(نسبی یا مطلق):',
		'maintenance_admin_only' => 'سایت در حال نگهداری است و موقتا قابل یهره برداری نمی باشد.',
		'maximum_x' => ' (max ^)',
		'mysql_version' => 'نگارش MySQL:',
		'nav_links_explanation' => 'پیوندهای زیر در تمامی صفحات نمایش داده شوند:',
		'nav_qa_is_home' => 'پرسشها و پاسخهایی که در صفحه اصلی باید نمایش داده شوند',
		'neat_urls_note' => ' (نیازمند htaccess می باشد)',
		'no_classification' => 'فاقد طبقه بندی',
		'no_hidden_found' => 'هیچ پرسش/پاسخ و یا نظر مخفی وجود ندارد.',
		'no_image_gd' => 'The installed version of PHP was compiled without GD image support, so users cannot upload their avatars directly.',
		'no_link' => 'بدون پیوند',
		'no_multibyte' => 'The installed version of PHP was compiled without multibyte string support. Searching will be less effective for non-Roman characters.',
		'no_plugin_options' => 'افزونه های نصب شده فاقد تنظیمات سفارشی می باشند.',
		'no_privileges' => 'این صفحه تنها برای مدیر قابل دسترسی می باشد.',
		'not_logged_in' => 'جهت دسترسی به این بخش باید اول ^1وارد^2 سایت شده باشید.',
		'opposite_main_menu' => 'در پایان منوی اصلی',
		'options_reset' => 'تنظیمات بازنشانی شد',
		'options_saved' => 'تنظیمات ذخیره شد',
		'page_already_used' => 'این موضوع در حال حاضر توسط یک صفحه دیگر مورد استفاده قرار گرفته شده است.',
		'page_content_html' => 'محتویات صفحه(HTML):',
		'page_default_slug' => 'صفحه-^',
		'page_heading' => 'عنوان نمایش داده شده در بالای صفحات:',
		'page_name' => 'نام صفحه(قابل استفاده در منوها و پیوندها):',
		'page_slug' => 'نشانی مستعار صفحه(URL fragment):',
		'pages_explanation' => 'در \'صفحه جدید\' برای افزودن صفحه سفارشی به سایت کلیک کنید و یا, در \'پیوند جدید\' برای پیوند دهی با سایر قسمتهای سایت کلیک نمایید.',
		'pages_title' => 'صفحات',
		'permissions_title' => 'مجوزها',
		'php_version' => 'نگارش PHP:',
		'plugin_pages_explanation' => 'صفحات زیر توسط افزونه ها قابل استفاده می باشند:',
		'plugins_title' => 'افزونه ها',
		'points_defaults_shown' => 'مقادیر پیشگزیده زیر قابل استفاده اند اما تاکنون مورد استفاده قرار نگرفته اند:',
		'points_required' => 'امتیاز لازیم برای دریافت این مدال:',
		'points_title' => 'امتیاز',
		'points' => 'امتیاز',
		'position' => 'محل:',
		'posting_title' => 'عنوان پست',
		'profile_fields' => 'سایر فیلدها در نمایه کاربر:',
		'q2a_db_version' => 'ورژن بانک اطلاعاتی:',
		'q2a_latest_version' => 'آخرین نگارش Q2A:',
		'q2a_version' => 'ورژن:',
		'recalc_categories_complete' => 'همه طبقه بندیها مجدد محاسبه گردیدند.',
		'recalc_categories_note' => ' - برای شمارش و محاسبه مجدد طبقه بندیها',
		'recalc_categories_recounting' => 'در حال محاسبه تعداد طبقات و پرسشها و...',
		'recalc_categories_updated' => '^1 of ^2 پاسخ و نظر محاسبه گردید...',
		'recalc_categories' => 'محاسبه مجدد طبقه بندیها',
		'recalc_points_complete' => 'امتیاز تمامی کاربران مجددا محاسبه گردید.',
		'recalc_points_note' => ' - قابل استفاده در رتبه بندی کاربران',
		'recalc_points_recalced' => 'محاسبه مجدد ^1 of ^2 کاربران...',
		'recalc_points_usercount' => 'برآورد تعداد کاربران...',
		'recalc_points' => 'محاسبه مجدد امتیاز کاربران',
		'recalc_posts_count' => 'مشاهده تعداد کل پرسشها/نظرات و پستها...',
		'recalc_stop' => 'توقف عملیات محاسبه مجدد',
		'recaptcha_fsockopen' => 'To use reCAPTCHA, the fsockopen() PHP function must be enabled on your server. Please check with your system administrator.',
		'recaptcha_get_keys' => 'To use reCAPTCHA, you must ^1sign up^2 to get these keys.',
		'recent_hidden_title' => 'آخرین پرسشهای حاوی محتوای مخفی',
		'recount_posts_complete' => 'تمامی پرسشها و پاسخها با موفقیت محاسبه گردید',
		'recount_posts_note' => ' - تعداد پاسخها و آراء به ازای هر پست',
		'recount_posts_recounted' => 'محاسبه مجدد ^1 of ^2 پرسشها و پاسخها...',
		'recount_posts_stop' => 'توقف محاسبه مجدد',
		'recount_posts' => 'بازشماری پرسشها و پاسخها',
		'reindex_posts_complete' => 'تمامی پرسشها و پاسخها و نظرات فهرستگذاری شد',
		'reindex_posts_note' => ' - قابل استفاده در جستجو و پیشنهاد عبارات احتمالی در آن',
		'reindex_posts_reindexed' => 'فهرستگذاری ^1 of ^2 پرسش،پاسخ و نظر...',
		'reindex_posts_stop' => 'توقف فهرستگذاری',
		'reindex_posts_wordcounted' => 'بازشماری ^1 of ^2 واژه...',
		'reindex_posts' => 'فهرستگذاری پرسشها،پاسخها و نظرات',
		'requires_q2a_version' => 'غیر فعال-نیازمند نگارش دیگری از این برنامه',
		'reset_options_button' => 'مقادیر پیشگزیده',
		'save_options_button' => 'ذخیره تنظیمات',
		'save_recalc_button' => 'ذخیره و محاسبه مجدد',
		'show_defaults_button' => 'نمایش مقادیر پیشگزیده',
		'slug_bad_chars' => 'نشانی مستعار می تواند شامل حروف مقابل نباشد: ^',
		'slug_reserved' => 'این نشانی مستعار قبلا برای صفحه دیگری استفاده شده است',
		'spam_title' => 'هرزنامه',
		'stats_title' => 'آمار',
		'stop_recalc_warning' => 'عملیات نگهداری بانک اطلاعاتی در حال اجرا می باشد.اگر این پنرجه بسته شود این عملیات متوقف می شود.',
		'tags_and_categories' => 'برچسبها و طبقه بندیها',
		'tags_not_shown' => 'برخی از پرسشهای پرجسب دار نمایش داده نخواهند شد.',
		'tags' => 'برچسبها',
		'title_already_used' => 'این مقدار قبلا توسط عنوان دیگری مورد استفاده قرار گرفته است.',
		'total_as' => 'تعداد پاسخها:',
		'total_cs' => 'نعداد نظرها:',
		'total_qs' => 'تعداد پرسشها:',
		'unnamed_plugin' => 'افزونه بی نام',
		'upgrade_db' => 'Your Question2Answer database needs to be ^1upgraded^2 for this version.',
		'url_format_note' => 'مقادیر همراه ^ برای تنظیمات پیکره بندی سایت بکار می روند.',
		'user_title' => 'عنوان کاربر(HTML):',
		'user_titles' => 'عنوان کاربر بر اساس امتیاز:',
		'users_active' => 'کاربران فعال:',
		'users_posted' => 'کاربرانیکه دارای پست هستند:',
		'users_registered' => 'کاربران عضو:',
		'users_title' => 'کاربران',
		'users_voted' => 'کاربرانیکه رای داده اند:',
		'viewing_title' => 'نما/نمایش',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
